export enum ResponseErrorReason {
	Failed = 'Failed',
	Aborted = 'Aborted',
	TimedOut = 'TimedOut',
	AccessDenied = 'AccessDenied',
	ConnectionClosed = 'ConnectionClosed',
	ConnectionReset = 'ConnectionReset',
	ConnectionRefused = 'ConnectionRefused',
	ConnectionAborted = 'ConnectionAborted',
	ConnectionFailed = 'ConnectionFailed',
	NameNotResolved = 'NameNotResolved',
	InternetDisconnected = 'InternetDisconnected',
	AddressUnreachable = 'AddressUnreachable',
	BlockedByClient = 'BlockedByClient',
	BlockedByResponse = 'BlockedByResponse',
}

export const responseErrorReasonsList = [
	ResponseErrorReason.Failed,
	ResponseErrorReason.Aborted,
	ResponseErrorReason.TimedOut,
	ResponseErrorReason.AccessDenied,
	ResponseErrorReason.ConnectionClosed,
	ResponseErrorReason.ConnectionReset,
	ResponseErrorReason.ConnectionRefused,
	ResponseErrorReason.ConnectionAborted,
	ResponseErrorReason.ConnectionFailed,
	ResponseErrorReason.NameNotResolved,
	ResponseErrorReason.InternetDisconnected,
	ResponseErrorReason.AddressUnreachable,
	ResponseErrorReason.BlockedByClient,
	ResponseErrorReason.BlockedByResponse,
];

export const responseErrorReasonsHumanTitles: Record<ResponseErrorReason, string> = {
	[ResponseErrorReason.Failed]: 'Failed',
	[ResponseErrorReason.Aborted]: 'Aborted',
	[ResponseErrorReason.TimedOut]: 'Timed out',
	[ResponseErrorReason.AccessDenied]: 'Access denied',
	[ResponseErrorReason.ConnectionClosed]: 'Connection closed',
	[ResponseErrorReason.ConnectionReset]: 'Connection reset',
	[ResponseErrorReason.ConnectionRefused]: 'Connection refused',
	[ResponseErrorReason.ConnectionAborted]: 'Connection aborted',
	[ResponseErrorReason.ConnectionFailed]: 'Connection failed',
	[ResponseErrorReason.NameNotResolved]: 'Name not resolved',
	[ResponseErrorReason.InternetDisconnected]: 'Internet disconnected',
	[ResponseErrorReason.AddressUnreachable]: 'Address unreachable',
	[ResponseErrorReason.BlockedByClient]: 'Blocked by client',
	[ResponseErrorReason.BlockedByResponse]: 'Blocked by response',
};
